--- #YAML:1.0
name: Class-Persist
version: 0.30
license: perl
distribution_type: module
requires:
  Class::Accessor::Chained: 0
  Class::Data::Inheritable: 0
  DBI: 0.01
  Data::UUID: 0.01
  DateTime: 0.21
  Error: 0.15
  UNIVERSAL::require: 0.01
  perl: 5.008
recommends: {}
build_requires:
  DBD::SQLite: 0
  File::Find::Rule: 0
  Test::More: 0
  Test::Pod: 1.00
  Test::Simple: 0
conflicts: {}
provides:
  Class::Persist:
    file: lib/Class/Persist.pm
    version: 0.30
  Class::Persist::Base:
    file: lib/Class/Persist/Base.pm
  Class::Persist::Blob:
    file: lib/Class/Persist/Blob.pm
  Class::Persist::Cache:
    file: lib/Class/Persist/Cache.pm
  Class::Persist::Collection:
    file: lib/Class/Persist/Collection.pm
  Class::Persist::Proxy:
    file: lib/Class/Persist/Proxy.pm
generated_by: Module::Build version 0.21
